# Banco local via Docker Compose (DEV)
spring.datasource.url=jdbc:postgresql://localhost:5433/fotolanddb
spring.datasource.username=fotolanduser
spring.datasource.password=fotolandpass
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Log para desenvolvimento
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ARMAZENAMENTO LOCAL (Para rodar sem precisar de chaves da AWS)
storage.mode=local

# DESATIVAR TENTATIVAS DE CONEXÃO AWS EXTERNAS (Evita o Timeout 504)
cloud.aws.credentials.instance-profile=false
cloud.aws.stack.auto=false
cloud.aws.region.auto=false

# Forçar ouvir apenas no IPv4 para evitar lentidão do localhost no macOS
server.address=127.0.0.1
server.port=8888


# Desativar e-mail no dev para não travar o boot
spring.mail.host=localhost
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration

# Log detalhado de segurança para debug de 504
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
